### PR TITLE
fix: support for class within conditions and nested clause

### PR DESCRIPTION
**Pull request by supminn**
- Fix for #3 and #5
- These fixes are for [Multiple feature requests on ReactPlay](https://github.com/reactplay/react-play/issues/24)
I have tested it out with the examples present in `example/queries_v2/multiple-filters.js`

P.S: Request you to add `hacktoberfest` tag so that it could be considered too 😄

### CODE REVIEW

**Comment by supminn** [comment]
Hi @koustov 
Please review these changes. Once they are merged, I can get the [multiple filters](https://github.com/reactplay/react-play/issues/24) feature tested out on ReactPlay.

**Comment by koustov** [comment]
Hello @supminn , i just had a quick run and it looks great. Meanwhile, I also made some structural changes. Could you please update your branch? Then I will do a final review /merge and update the package.

**Comment by supminn** [comment]
> Hello @supminn , i just had a quick run and it looks great. Meanwhile, I also made some structural changes. Could you please update your branch? Then I will do a final review /merge and update the package.

Hi @koustov, I have got this branch merged with the latest updates from `main`.

**Comment by koustov** [comment]
I am testing it now. Once done I will merge and create a release

**Review by koustov — APPROVED** [review]
lgtm

**Comment by koustov** [comment]
@supminn I have published 0.1.8 version

**Pull request merged**
